name: docusaurus-workflow
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-docusaurus:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies and build docs
        run: |
          cd docs-site
          npm ci
          npm run build
      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd docs-site
          npm run deploy
