name: Build MSI Installer (Windows)

on:
  workflow_dispatch:

jobs:
  build-msi:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install WiX Toolset
        run: |
          choco install wixtoolset -y

      - name: Build Go app for Windows
        run: |
          mkdir dist
          cd src
          set GOOS=windows
          set GOARCH=amd64
          go build -o ..\dist\TunGo.exe .  # Build TunGo.exe

      - name: Copy icon file
        run: |
          copy docs\TunGo\static\img\favicon.ico dist\tungo.ico  # Copy icon for the installer

      - name: Download and extract Wintun
        run: |
          mkdir dist\wintun
          cd dist\wintun
          curl -L -o wintun.zip https://www.wintun.net/builds/wintun-0.14.1.zip
          tar -xf wintun.zip
          Move-Item -Force "wintun\bin\amd64\wintun.dll" ..\  # Move Wintun.dll to the dist folder

      - name: Generate installer.wxs
        run: |
          cd dist
          for /f %%i in ('uuidgen') do set UPGRADE_CODE=%%i
          for /f %%i in ('uuidgen') do set WINTUN_GUID=%%i
          for /f %%i in ('uuidgen') do set APP_GUID=%%i
          for /f "delims=" %%i in ('git describe --tags --abbrev=0 2^>nul') do set VERSION=%%i
          if not defined VERSION set VERSION=1.0.0
          rem Create installer.wxs with UI for choosing installation directory:
          (
            echo <?xml version="1.0"?>
            echo <Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
            echo   <Product Id="*" Name="TunGo" Language="1033" Version="%VERSION%" Manufacturer="TunGo Contributors" UpgradeCode="%UPGRADE_CODE%">
            echo     <Package InstallerVersion="500" Compressed="yes" InstallScope="perMachine" />
            echo     <Property Id="WIXUI_INSTALLDIR" Value="INSTALLFOLDER"/>
            echo     <Media Id="1" Cabinet="media1.cab" EmbedCab="yes"/>
            echo     <Icon Id="AppIcon" SourceFile="tungo.ico"/>
            echo     <Directory Id="TARGETDIR" Name="SourceDir">
            echo       <Directory Id="ProgramFilesFolder">
            echo         <Directory Id="INSTALLFOLDER" Name="TunGo">
            echo           <Component Id="AppExe" Guid="%APP_GUID%">
            echo             <File Id="AppFile" Name="TunGo.exe" Source="TunGo.exe">
            echo               <Shortcut Id="DesktopShortcut" Directory="DesktopFolder" Name="TunGo" Description="Starting TunGo in client mode" WorkingDirectory="INSTALLFOLDER" Arguments="c" Icon="AppIcon" IconIndex="0"/>
            echo             </File>
            echo             <RegistryValue Root="HKLM" Key="Software\TunGo" Name="installed" Type="integer" Value="1" KeyPath="yes"/>
            echo           </Component>
            echo         </Directory>
            echo       </Directory>
            echo       <Directory Id="SystemFolder">
            echo         <Component Id="WintunDLL" Guid="%WINTUN_GUID%">
            echo           <File Id="WintunFile" Name="wintun.dll" Source="wintun.dll" />
            echo         </Component>
            echo       </Directory>
            echo     </Directory>
            echo     <Feature Id="DefaultFeature" Level="1">
            echo       <ComponentRef Id="AppExe" />
            echo       <ComponentRef Id="WintunDLL" />
            echo     </Feature>
            echo     <UI>
            echo       <UIRef Id="WixUI_InstallDir" />
            echo     </UI>
            echo   </Product>
            echo </Wix>
          ) > installer.wxs

      - name: Build MSI installer
        run: |
          cd dist
          candle.exe installer.wxs  # Compile WiX source
          light.exe -ext WixUIExtension installer.wixobj -o tungo.msi  # Link to generate MSI

      - name: Upload MSI artifact
        uses: actions/upload-artifact@v4
        with:
          name: tungo-msi
          path: dist\tungo.msi
