name: Build TunGo.exe for win amd64

on:
  workflow_dispatch:

jobs:
  build-exe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Go app for Windows
        run: |
          mkdir -p dist
          cd src
          GOOS=windows GOARCH=amd64 go build -o ../dist/TunGo.exe .

      - name: Upload TunGo.exe artifact
        uses: actions/upload-artifact@v4
        with:
          name: TunGo-exe
          path: dist/TunGo.exe
