name: Build MSI Installer (Windows)

on:
  workflow_dispatch:

jobs:
  build-msi:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install WiX Toolset
        run: |
          choco install wixtoolset -y  # Install WiX Toolset via Chocolatey

      - name: Build Go app for Windows
        run: |
          mkdir dist
          cd src
          set GOOS=windows
          set GOARCH=amd64
          go build -o ..\dist\TunGo.exe .  # Build TunGo.exe

      - name: Copy icon file
        run: |
          copy docs\TunGo\static\img\favicon.ico dist\tungo.ico  # Copy icon for the installer

      - name: Download and extract Wintun
        run: |
          mkdir dist\wintun
          cd dist\wintun
          curl -L -o wintun.zip https://www.wintun.net/builds/wintun-0.14.1.zip
          tar -xf wintun.zip
          Move-Item -Force "wintun\bin\amd64\wintun.dll" ..\  # Move Wintun.dll to the dist folder

      - name: Generate installer.wxs
        shell: powershell
        run: |
          Set-Location dist
          # Generate GUIDs and get version from Git tags
          $UPGRADE_CODE = [guid]::NewGuid().ToString()
          $WINTUN_GUID = [guid]::NewGuid().ToString()
          $APP_GUID     = [guid]::NewGuid().ToString()
          $VERSION = (& git describe --tags --abbrev=0 2>$null)
          if (-not $VERSION) { $VERSION = "1.0.0" }
          # Create installer.wxs with a here-string
          $wxsContent = @"
          <?xml version="1.0"?>
          <Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
            <Product Id="*" Name="TunGo" Language="1033" Version="$VERSION" Manufacturer="TunGo Contributors" UpgradeCode="$UPGRADE_CODE">
              <Package InstallerVersion="500" Compressed="yes" InstallScope="perMachine" />
              <Property Id="WIXUI_INSTALLDIR" Value="INSTALLFOLDER"/>
              <Media Id="1" Cabinet="media1.cab" EmbedCab="yes"/>
              <Icon Id="AppIcon" SourceFile="tungo.ico"/>
              <Directory Id="TARGETDIR" Name="SourceDir">
                <Directory Id="ProgramFilesFolder">
                  <Directory Id="INSTALLFOLDER" Name="TunGo">
                    <Component Id="AppExe" Guid="$APP_GUID">
                      <File Id="AppFile" Name="TunGo.exe" Source="TunGo.exe">
                        <Shortcut Id="DesktopShortcut" Directory="DesktopFolder" Name="TunGo" Description="Starting TunGo in client mode" WorkingDirectory="INSTALLFOLDER" Arguments="c" Icon="AppIcon" IconIndex="0"/>
                      </File>
                      <RegistryValue Root="HKLM" Key="Software\TunGo" Name="installed" Type="integer" Value="1" KeyPath="yes"/>
                    </Component>
                  </Directory>
                </Directory>
                <Directory Id="SystemFolder">
                  <Component Id="WintunDLL" Guid="$WINTUN_GUID">
                    <File Id="WintunFile" Name="wintun.dll" Source="wintun.dll" />
                  </Component>
                </Directory>
              </Directory>
              <Feature Id="DefaultFeature" Level="1">
                <ComponentRef Id="AppExe" />
                <ComponentRef Id="WintunDLL" />
              </Feature>
              <UI>
                <UIRef Id="WixUI_InstallDir" />
              </UI>
            </Product>
          </Wix>
          "@
          # Write the content to installer.wxs
          $wxsContent | Out-File -FilePath installer.wxs -Encoding utf8

      - name: Build MSI installer
        run: |
          cd dist
          candle.exe installer.wxs  # Compile WiX source
          light.exe -ext WixUIExtension installer.wixobj -o tungo.msi  # Link to generate MSI

      - name: Upload MSI artifact
        uses: actions/upload-artifact@v4
        with:
          name: tungo-msi
          path: dist\tungo.msi
