name: Build MSI Installer

on:
  workflow_dispatch:

jobs:
  build-msi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y msitools uuid-runtime unzip wixl

      - name: Build Go app for Windows
        run: |
          mkdir -p dist
          cd src
          GOOS=windows GOARCH=amd64 go build -o ../dist/app.exe .

      - name: Download and extract Wintun
        run: |
          mkdir -p dist
          cd dist
          curl -L -o wintun.zip https://www.wintun.net/builds/wintun-0.14.1.zip
          unzip wintun.zip
          mv 'wintun/bin/amd64/wintun.dll' .

      - name: Generate installer.wxs
        run: |
          cd dist
              UPGRADE_CODE=$(uuidgen)
              WINTUN_GUID=$(uuidgen)
              APP_GUID=$(uuidgen)
          cat <<'EOFXML' > installer.wxs
          <?xml version="1.0"?>
          <Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
            <Product Id="*" Name="Tungo" Language="1033" Version="1.0.0.0" Manufacturer="TunGo org" UpgradeCode="${UPGRADE_CODE}">
              <Package InstallerVersion="500" Compressed="yes" InstallScope="perMachine" />
              <Media Id="1" Cabinet="media1.cab" EmbedCab="yes"/>
              <Directory Id="TARGETDIR" Name="SourceDir">
                <Directory Id="SystemFolder">
                  <Component Id="WintunDLL" Guid="${WINTUN_GUID}">
                    <File Id="WintunFile" Name="wintun.dll" Source="wintun.dll" />
                  </Component>
                </Directory>
                <Directory Id="ProgramFilesFolder">
                  <Directory Id="INSTALLFOLDER" Name="Tungo">
                    <Component Id="AppExe" Guid="${APP_GUID}">
                      <File Id="AppFile" Name="app.exe" Source="app.exe" />
                    </Component>
                  </Directory>
                </Directory>
              </Directory>
              <Feature Id="DefaultFeature" Level="1">
                <ComponentRef Id="WintunDLL" />
                <ComponentRef Id="AppExe" />
              </Feature>
            </Product>
          </Wix>
          EOFXML


      - name: Build MSI installer
        run: |
          cd dist
          wixl -o tungo.msi installer.wxs
      
      - name: Upload MSI artifact
        uses: actions/upload-artifact@v4
        with:
          name: tungo-msi
          path: dist/tungo.msi
